
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

server:
  port: 8080
spring:
  application:
    name: meng-pay
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      async-close-connection-enable: true
      initial-size: 2
      max-active: 30
      max-pool-prepared-statement-per-connection-size: 5
      max-wait: 10000
      min-evictable-idle-time-millis: 30001
      min-idle: 2
      pool-prepared-statements: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      validation-query: select 1
      validation-query-timeout: 1
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    username: root

    url: jdbc:mysql://29.157.17.108:16063/bmsdb?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: bms
    password: Ce_Sh1.Pa2s_mydb
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
