server:
  port: 8081
spring:
  application:
    name: meng-pay
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
alipay:
  # 商户私钥，您的PKCS8格式RSA2私钥
  privateKey:
  # 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
  publicKey:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  appId:
  #
  charset: UTF-8
  # 支付宝网关
  gatewayUrl: https://openapi.alipay.com/gateway.do
  # 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  # e.g.
  notifyUrl:
  # 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  returnUrl:
  # 签名方式
  signType: RSA2