mybatis:
  mapper-locations: classpath*:/*mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 31006
spring:
  application:
    name: sharding-sphere-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  datasource:
    db:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        async-close-connection-enable: true
        initialSize: 5  # 初始化大小
        minIdle: 5  # 最小连接数
        maxActive: 200 # 最大连接数
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        testWhileIdle: true
        testOnBorrow: false #获取连接时先验证连接是否有效
        testOnReturn: false #归还连接时先验证连接是否有效
        time-between-eviction-runs-millis: 10000
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1

        filters: config,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        decrypt: #自定义的配置文件 druid 加密密码使用的公钥
          publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKj++E3CdByr53zfduZmmvqOd75l+564n1ICrv5p8rHav6J9YbtohBvM6DvWzK37XVtAWvxEdOPZBOkto6Q+yG0CAwEAAQ=="
          password: "D7JWG6uh3Z/yUlZxRpo3PgwSjokS3AW1jIBjLvHTHsag1xryr3UiY8+ai3FozzScgTGap+iBGBXczyJJ2Y2kYA=="
        connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
      url: jdbc:mysql://169.254.97.211:3306/db?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456

    db2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        async-close-connection-enable: true
        initialSize: 5  # 初始化大小
        minIdle: 5  # 最小连接数
        maxActive: 200 # 最大连接数
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        testWhileIdle: true
        testOnBorrow: false #获取连接时先验证连接是否有效
        testOnReturn: false #归还连接时先验证连接是否有效
        time-between-eviction-runs-millis: 10000
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1

        filters: config,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        decrypt: #自定义的配置文件 druid 加密密码使用的公钥
          publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKj++E3CdByr53zfduZmmvqOd75l+564n1ICrv5p8rHav6J9YbtohBvM6DvWzK37XVtAWvxEdOPZBOkto6Q+yG0CAwEAAQ=="
          password: "D7JWG6uh3Z/yUlZxRpo3PgwSjokS3AW1jIBjLvHTHsag1xryr3UiY8+ai3FozzScgTGap+iBGBXczyJJ2Y2kYA=="
        connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
      url: jdbc:mysql://29.157.17.108:16063/db?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456

    db3:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        async-close-connection-enable: true
        initialSize: 5  # 初始化大小
        minIdle: 5  # 最小连接数
        maxActive: 200 # 最大连接数
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        testWhileIdle: true
        testOnBorrow: false #获取连接时先验证连接是否有效
        testOnReturn: false #归还连接时先验证连接是否有效
        time-between-eviction-runs-millis: 10000
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1

        filters: config,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        decrypt: #自定义的配置文件 druid 加密密码使用的公钥
          publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKj++E3CdByr53zfduZmmvqOd75l+564n1ICrv5p8rHav6J9YbtohBvM6DvWzK37XVtAWvxEdOPZBOkto6Q+yG0CAwEAAQ=="
          password: "D7JWG6uh3Z/yUlZxRpo3PgwSjokS3AW1jIBjLvHTHsag1xryr3UiY8+ai3FozzScgTGap+iBGBXczyJJ2Y2kYA=="
        connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
      url: jdbc:mysql://169.254.97.211:3306/db?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456

    db4:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        async-close-connection-enable: true
        initialSize: 5  # 初始化大小
        minIdle: 5  # 最小连接数
        maxActive: 200 # 最大连接数
        maxWait: 60000 # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
        testWhileIdle: true
        testOnBorrow: false #获取连接时先验证连接是否有效
        testOnReturn: false #归还连接时先验证连接是否有效
        time-between-eviction-runs-millis: 10000
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1

        filters: config,stat,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        decrypt: #自定义的配置文件 druid 加密密码使用的公钥
          publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKj++E3CdByr53zfduZmmvqOd75l+564n1ICrv5p8rHav6J9YbtohBvM6DvWzK37XVtAWvxEdOPZBOkto6Q+yG0CAwEAAQ=="
          password: "D7JWG6uh3Z/yUlZxRpo3PgwSjokS3AW1jIBjLvHTHsag1xryr3UiY8+ai3FozzScgTGap+iBGBXczyJJ2Y2kYA=="
        connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        useGlobalDataSourceStat: false # 合并多个DruidDataSource的监控数据
      url: jdbc:mysql://169.254.97.211:3306/db?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
